---
- hosts: localhost
  connection: local
  gather_facts: False
  
  vars:
    key_name: eng84devops
    image: ami-038d7b856fe7557b3
    pub_sec_group: sg-00aa81fddf8fca6bc
    priv_sec_group: sg-08073833103f10c18
    pub_subnet_id: subnet-0b96bde6482352562
    priv_subnet_id: subnet-0b3635644a18d4e6c
    region: eu-west-1
  
  tasks:
    
    - name: Facts
      block:
        - name: Get instance facts
          ec2_instance_facts:
            aws_access_key: "{{aws_access_key}}"
            aws_secret_key: "{{aws_secret_key}}"
            region: "{{ region }}"
          register: result

        - name: Instances ID
          debug:
            msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
          loop: "{{ result.instances }}"

      tags: always

    - name: Provisioning an ec2
      block:
      - name: Provision controller instance(s)
        ec2:
          aws_access_key: "{{aws_access_key}}"
          aws_secret_key: "{{aws_secret_key}}"
          key_name: "{{ key_name }}"
          vpc_subnet_id: "{{ pub_subnet_id }}"
          group_id: "{{ pub_sec_group }}"
          image: ami-0943382e114f188e8
          instance_type: t2.micro
          region: "{{ region }}"
          wait: true
          count: 1
          assign_public_ip: yes
          instance_tags:
            Name: eng84_ben_ansible_controller

      tags: always
