#
---

- hosts: web
  gather_facts: yes
  become: true

  tasks:
  - name: update
    shell:
      cmd: apt-get update -y
  

  - name: upgrade
    shell:
      cmd: apt-get upgrade -y

  
  - name: Install Nginx
    apt: pkg=nginx state=present


  - name: Install PythonSoftwareProperties
    apt: pkg=python-software-properties state=present


  - name: Install npm
    apt: pkg=npm state=present


  - name: create nodeFile
    file:
      state: touch
      path: /home/ubuntu/nodeSetup.sh
      mode: 0777

  - name: add node source
    shell: 
      cmd: runuser -l ubuntu -c 'sudo curl -sL https://deb.nodesource.com/setup_6.x > /home/ubuntu/nodeSetup.sh'
  
  - name: run Script
    shell: 
      cmd: bash /home/ubuntu/nodeSetup.sh
  
  - name: cleanup files
    file:
      state: absent
      path: /home/ubuntu/nodeSetup.sh  
  
  - name: Install nodejs
    shell: sudo apt-get install nodejs -y

  - name: Install pm2
    shell:
      cmd: npm install -g pm2	
  
  - name: Install tmux
    apt: pkg=tmux state=present

  - name: Refresh git
    file:
      state: absent
      path: /home/ubuntu/eng84_cicd
  
  - name: Redownloading from git   
    shell:
      cmd: git clone https://github.com/Benoniy/eng84_cicd

    
  - name: fix nginx
    shell:
      cmd: mv /home/ubuntu/eng84_cicd/environment/app/nginx.default /etc/nginx/sites-available/default
  

  - name: Enable nginx at boot
    service: name=nginx state=restarted enabled=yes
 

  - name: NPM install
    npm:
      path: /home/ubuntu/eng84_cicd/app

  - name: export DBHOST
    lineinfile:
      path: /home/ubuntu/.bashrc
      line: export DB_HOST=mongodb://66.66.2.36:27017/posts
